# Generated by Django 4.2.1 on 2023-10-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('cooking_steps', models.TextField(blank=True)),
                ('cooking_time', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=40)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
