# Generated by Django 4.2.1 on 2023-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='recipes',
            index=models.Index(fields=['-create_time'], name='recipes_rec_create__f67b3a_idx'),
        ),
    ]
