# Generated by Django 4.2.1 on 2023-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_options_recipes_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
