# Generated by Django 4.2.1 on 2023-10-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_category_recipes_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.category'),
        ),
    ]
